import type { DiagramSpec } from "../types.ts";

export const reviewDemoDiagram: DiagramSpec = {
  id: "review-demo",
  outputFile: "assets/review-demo.html",
  galleryBaseName: "anthropic_theme_flowchart_review_demo",
  pageTitle: "Anthropic Theme Flowchart Demo",
  ariaLabel: "Anthropic grouped flowchart demo",
  header: {
    eyebrow: "Anthropic Theme Flowchart",
  },
  columns: [
    { id: "primary-column", width: 680 },
    { id: "bridge-column", width: 132 },
    { id: "secondary-column", width: 324 },
  ],
  spaces: [
    {
      id: "primary",
      panelKind: "lane",
      panelClass: "lane",
      columnId: "primary-column",
      width: 640,
      height: 448,
      diagramX: 20,
      diagramY: 0,
      title: "Pi session",
      titlePlacement: "outside",
      outerFrame: true,
    },
    {
      id: "bridge",
      panelKind: "bridge",
      panelClass: "bridge-column",
      columnId: "bridge-column",
      width: 132,
      height: 448,
      diagramX: 680,
      diagramY: 0,
      commentLines: [
        "Bridge connector geometry in bridge-column coordinates",
        "Primary SVG origin: (20, 0)",
        "Bridge SVG origin: (680, 0)",
        "Secondary SVG origin: (812, -38)",
      ],
    },
    {
      id: "secondary",
      panelKind: "panel",
      panelClass: "secondary-panel",
      columnId: "secondary-column",
      width: 324,
      height: 448,
      diagramX: 812,
      diagramY: -38,
      title: "Background analyzer (cron / launchd)",
      titlePlacement: "inside-frame",
      svgFrame: {
        x: 2,
        y: 2,
        width: 320,
        height: 290,
      },
    },
  ],
  nodes: [
    {
      id: "session-events",
      spaceId: "primary",
      x: 26,
      y: 22,
      width: 208,
      height: 64,
      tone: "lavender",
      title: "Session events",
    },
    {
      id: "observation",
      spaceId: "primary",
      x: 26,
      y: 188,
      width: 208,
      height: 72,
      tone: "mint",
      title: "Observation",
      subtitle: "collector",
    },
    {
      id: "system-prompt",
      spaceId: "primary",
      x: 350,
      y: 188,
      width: 208,
      height: 72,
      tone: "teal",
      title: "System prompt",
      subtitle: "injection",
    },
    {
      id: "feedback-loop",
      spaceId: "primary",
      x: 356,
      y: 338,
      width: 196,
      height: 64,
      tone: "lavender",
      title: "Feedback loop",
    },
    {
      id: "reads-observations",
      spaceId: "secondary",
      x: 22,
      y: 48,
      width: 256,
      height: 64,
      tone: "cream",
      title: "Reads observations",
    },
    {
      id: "haiku-llm",
      spaceId: "secondary",
      x: 22,
      y: 180,
      width: 256,
      height: 76,
      tone: "amber",
      title: "Haiku LLM",
      subtitle: "analyses patterns",
    },
    {
      id: "instinct-files",
      spaceId: "secondary",
      x: 22,
      y: 320,
      width: 256,
      height: 72,
      tone: "peach",
      title: "Instinct files",
      subtitle: ".md + YAML frontmatter",
    },
  ],
  edges: [
    {
      id: "session-to-observation",
      spaceId: "primary",
      from: { nodeId: "session-events", side: "south" },
      to: { nodeId: "observation", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "observation-to-system",
      spaceId: "primary",
      from: { nodeId: "observation", side: "east" },
      to: { nodeId: "system-prompt", side: "west" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "system-to-feedback",
      spaceId: "primary",
      from: { nodeId: "system-prompt", side: "south" },
      to: { nodeId: "feedback-loop", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "feedback-to-observation",
      spaceId: "primary",
      from: { nodeId: "feedback-loop", side: "west" },
      to: { nodeId: "observation", side: "south" },
      route: { kind: "hv" },
      style: "soft",
      arrows: "end",
      comment: "Feedback loop west-center -> Observation south-center",
      label: {
        lines: ["records outcomes"],
        x: 118,
        y: 310,
      },
    },
    {
      id: "reads-to-haiku",
      spaceId: "secondary",
      from: { nodeId: "reads-observations", side: "south" },
      to: { nodeId: "haiku-llm", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "haiku-to-instinct",
      spaceId: "secondary",
      from: { nodeId: "haiku-llm", side: "south" },
      to: { nodeId: "instinct-files", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
      label: {
        lines: ["creates / updates"],
        x: 190,
        y: 302,
      },
    },
    {
      id: "instinct-stub",
      spaceId: "secondary",
      from: { nodeId: "instinct-files", side: "west" },
      to: {
        spaceId: "secondary",
        point: { x: 0, y: 356 },
        label: "bridge column boundary",
      },
      route: { kind: "straight" },
      arrows: "none",
      comment: "Instinct files west-center -> bridge column boundary",
    },
    {
      id: "instinct-to-system-bridge",
      spaceId: "bridge",
      from: {
        spaceId: "bridge",
        point: { x: 154, y: 318 },
        label: "Instinct files west-center",
      },
      to: {
        spaceId: "bridge",
        point: { x: -102, y: 224 },
        label: "System prompt east-center",
      },
      route: { kind: "hvh", x: 78 },
      arrows: "end",
      comment: "Instinct files west-center -> System prompt east-center",
      label: {
        lines: ["high-confidence", "instincts injected"],
        x: 68,
        y: 276,
        anchor: "middle",
      },
    },
  ],
};
