import type { DiagramSpec } from "../types.ts";

export const templateDiagram: DiagramSpec = {
  id: "anthropic-flowchart-template",
  outputFile: "assets/anthropic-flowchart-template.html",
  pageTitle: "Anthropic Flowchart Template",
  ariaLabel: "Grouped process flow",
  header: {
    eyebrow: "Pastel Grouped Flowchart",
    title: "Flowchart Title",
    description:
      "Replace this paragraph with one short framing sentence. This template uses a deterministic TS-first geometry layer so cards and connectors share explicit anchor points instead of hand-maintained SVG coordinates.",
  },
  columns: [
    { id: "primary-column", width: 680 },
    { id: "bridge-column", width: 132 },
    { id: "secondary-column", width: 324 },
  ],
  spaces: [
    {
      id: "primary",
      panelKind: "lane",
      panelClass: "lane",
      columnId: "primary-column",
      width: 640,
      height: 448,
      diagramX: 20,
      diagramY: 0,
      title: "Primary lane",
      titlePlacement: "outside",
      outerFrame: true,
    },
    {
      id: "bridge",
      panelKind: "bridge",
      panelClass: "bridge-column",
      columnId: "bridge-column",
      width: 132,
      height: 448,
      diagramX: 680,
      diagramY: 0,
      commentLines: [
        "Bridge connector geometry in bridge-column coordinates",
        "Use this space for cross-lane edges after converting both anchors into bridge-local coordinates.",
      ],
    },
    {
      id: "secondary",
      panelKind: "panel",
      panelClass: "secondary-panel",
      columnId: "secondary-column",
      width: 324,
      height: 448,
      diagramX: 812,
      diagramY: -38,
      title: "Background lane",
      titlePlacement: "inside-frame",
      svgFrame: {
        x: 2,
        y: 2,
        width: 320,
        height: 290,
      },
    },
  ],
  nodes: [
    {
      id: "upstream-signal",
      spaceId: "primary",
      x: 26,
      y: 22,
      width: 208,
      height: 64,
      tone: "lavender",
      title: "Upstream signal",
    },
    {
      id: "observation",
      spaceId: "primary",
      x: 26,
      y: 188,
      width: 208,
      height: 72,
      tone: "mint",
      title: "Observation",
      subtitle: "collector",
    },
    {
      id: "system-prompt",
      spaceId: "primary",
      x: 350,
      y: 188,
      width: 208,
      height: 72,
      tone: "teal",
      title: "System prompt",
      subtitle: "injection",
    },
    {
      id: "feedback-loop",
      spaceId: "primary",
      x: 356,
      y: 338,
      width: 196,
      height: 64,
      tone: "lavender",
      title: "Feedback loop",
    },
    {
      id: "batch-reader",
      spaceId: "secondary",
      x: 22,
      y: 48,
      width: 256,
      height: 64,
      tone: "cream",
      title: "Batch reader",
    },
    {
      id: "llm-analyzer",
      spaceId: "secondary",
      x: 22,
      y: 180,
      width: 256,
      height: 76,
      tone: "amber",
      title: "LLM analyzer",
      subtitle: "finds patterns and proposes updates",
    },
    {
      id: "output-artifacts",
      spaceId: "secondary",
      x: 22,
      y: 320,
      width: 256,
      height: 72,
      tone: "peach",
      title: "Output artifacts",
      subtitle: "creates reusable instruction files",
    },
  ],
  edges: [
    {
      id: "upstream-to-observation",
      spaceId: "primary",
      from: { nodeId: "upstream-signal", side: "south" },
      to: { nodeId: "observation", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "observation-to-system",
      spaceId: "primary",
      from: { nodeId: "observation", side: "east" },
      to: { nodeId: "system-prompt", side: "west" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "system-to-feedback",
      spaceId: "primary",
      from: { nodeId: "system-prompt", side: "south" },
      to: { nodeId: "feedback-loop", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "feedback-to-observation",
      spaceId: "primary",
      from: { nodeId: "feedback-loop", side: "west" },
      to: { nodeId: "observation", side: "south" },
      route: { kind: "hv" },
      arrows: "end",
      style: "soft",
      label: {
        lines: ["records outcomes"],
        x: 118,
        y: 310,
      },
    },
    {
      id: "batch-to-llm",
      spaceId: "secondary",
      from: { nodeId: "batch-reader", side: "south" },
      to: { nodeId: "llm-analyzer", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
    },
    {
      id: "llm-to-artifacts",
      spaceId: "secondary",
      from: { nodeId: "llm-analyzer", side: "south" },
      to: { nodeId: "output-artifacts", side: "north" },
      route: { kind: "straight" },
      arrows: "end",
      label: {
        lines: ["creates / updates"],
        x: 190,
        y: 302,
      },
    },
    {
      id: "artifacts-stub",
      spaceId: "secondary",
      from: { nodeId: "output-artifacts", side: "west" },
      to: {
        spaceId: "secondary",
        point: { x: 0, y: 356 },
        label: "bridge column boundary",
      },
      route: { kind: "straight" },
      arrows: "none",
      comment: "Output artifacts west-center -> bridge column boundary",
    },
    {
      id: "artifacts-to-system",
      spaceId: "bridge",
      from: {
        spaceId: "bridge",
        point: { x: 154, y: 318 },
        label: "Output artifacts west-center",
      },
      to: {
        spaceId: "bridge",
        point: { x: -102, y: 224 },
        label: "System prompt east-center",
      },
      route: { kind: "hvh", x: 78 },
      arrows: "end",
      comment: "Output artifacts west-center -> System prompt east-center",
      label: {
        lines: ["high-confidence", "signals injected"],
        x: 68,
        y: 276,
        anchor: "middle",
      },
    },
  ],
};
