import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { renderDiagram } from "./render.ts";
import { renderDiagramSvg } from "./render-svg.ts";
import { reviewDemoDiagram } from "./diagrams/review-demo.ts";
import { templateDiagram } from "./diagrams/template.ts";
import type { DiagramSpec } from "./types.ts";

const diagrams: DiagramSpec[] = [templateDiagram, reviewDemoDiagram];

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(currentDir, "..");

async function writeDiagram(diagram: DiagramSpec): Promise<void> {
  const outputPath = path.resolve(projectRoot, diagram.outputFile);
  await mkdir(path.dirname(outputPath), { recursive: true });

  const html = `<!-- Generated by src/build.ts from TS specs. Do not edit by hand. -->\n${renderDiagram(diagram)}`;
  await writeFile(outputPath, html, "utf8");
  console.log(`wrote ${path.relative(projectRoot, outputPath)}`);

  if (diagram.galleryBaseName) {
    const galleryDir = path.resolve(projectRoot, "..", "gallery");
    await mkdir(galleryDir, { recursive: true });
    const svgPath = path.join(galleryDir, `${diagram.galleryBaseName}.svg`);
    await writeFile(svgPath, renderDiagramSvg(diagram), "utf8");
    console.log(`wrote ${path.relative(path.resolve(projectRoot, ".."), svgPath)}`);
  }
}

async function main(): Promise<void> {
  for (const diagram of diagrams) {
    await writeDiagram(diagram);
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
